# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ygj/Documents/GitHub/AcceleratedC++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ygj/Documents/GitHub/AcceleratedC++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ygj/Documents/GitHub/AcceleratedC++/CMakeFiles /Users/ygj/Documents/GitHub/AcceleratedC++//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ygj/Documents/GitHub/AcceleratedC++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 0-2

# Build rule for target.
0-2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 0-2
.PHONY : 0-2

# fast build rule for target.
0-2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-2.dir/build.make CMakeFiles/0-2.dir/build
.PHONY : 0-2/fast

#=============================================================================
# Target rules for targets named 0-10

# Build rule for target.
0-10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 0-10
.PHONY : 0-10

# fast build rule for target.
0-10/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-10.dir/build.make CMakeFiles/0-10.dir/build
.PHONY : 0-10/fast

#=============================================================================
# Target rules for targets named String_exer

# Build rule for target.
String_exer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 String_exer
.PHONY : String_exer

# fast build rule for target.
String_exer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/String_exer.dir/build.make CMakeFiles/String_exer.dir/build
.PHONY : String_exer/fast

#=============================================================================
# Target rules for targets named 1-1

# Build rule for target.
1-1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-1
.PHONY : 1-1

# fast build rule for target.
1-1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-1.dir/build.make CMakeFiles/1-1.dir/build
.PHONY : 1-1/fast

#=============================================================================
# Target rules for targets named 1-2

# Build rule for target.
1-2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-2
.PHONY : 1-2

# fast build rule for target.
1-2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-2.dir/build.make CMakeFiles/1-2.dir/build
.PHONY : 1-2/fast

#=============================================================================
# Target rules for targets named 1-3

# Build rule for target.
1-3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-3
.PHONY : 1-3

# fast build rule for target.
1-3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-3.dir/build.make CMakeFiles/1-3.dir/build
.PHONY : 1-3/fast

#=============================================================================
# Target rules for targets named 1-4

# Build rule for target.
1-4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-4
.PHONY : 1-4

# fast build rule for target.
1-4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-4.dir/build.make CMakeFiles/1-4.dir/build
.PHONY : 1-4/fast

#=============================================================================
# Target rules for targets named 1-5

# Build rule for target.
1-5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-5
.PHONY : 1-5

# fast build rule for target.
1-5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-5.dir/build.make CMakeFiles/1-5.dir/build
.PHONY : 1-5/fast

#=============================================================================
# Target rules for targets named 1-6

# Build rule for target.
1-6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-6
.PHONY : 1-6

# fast build rule for target.
1-6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-6.dir/build.make CMakeFiles/1-6.dir/build
.PHONY : 1-6/fast

#=============================================================================
# Target rules for targets named end_nl_exer

# Build rule for target.
end_nl_exer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 end_nl_exer
.PHONY : end_nl_exer

# fast build rule for target.
end_nl_exer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/end_nl_exer.dir/build.make CMakeFiles/end_nl_exer.dir/build
.PHONY : end_nl_exer/fast

chapter0/0-10.o: chapter0/0-10.cpp.o
.PHONY : chapter0/0-10.o

# target to build an object file
chapter0/0-10.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-10.dir/build.make CMakeFiles/0-10.dir/chapter0/0-10.cpp.o
.PHONY : chapter0/0-10.cpp.o

chapter0/0-10.i: chapter0/0-10.cpp.i
.PHONY : chapter0/0-10.i

# target to preprocess a source file
chapter0/0-10.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-10.dir/build.make CMakeFiles/0-10.dir/chapter0/0-10.cpp.i
.PHONY : chapter0/0-10.cpp.i

chapter0/0-10.s: chapter0/0-10.cpp.s
.PHONY : chapter0/0-10.s

# target to generate assembly for a file
chapter0/0-10.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-10.dir/build.make CMakeFiles/0-10.dir/chapter0/0-10.cpp.s
.PHONY : chapter0/0-10.cpp.s

chapter0/0-2.o: chapter0/0-2.cpp.o
.PHONY : chapter0/0-2.o

# target to build an object file
chapter0/0-2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-2.dir/build.make CMakeFiles/0-2.dir/chapter0/0-2.cpp.o
.PHONY : chapter0/0-2.cpp.o

chapter0/0-2.i: chapter0/0-2.cpp.i
.PHONY : chapter0/0-2.i

# target to preprocess a source file
chapter0/0-2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-2.dir/build.make CMakeFiles/0-2.dir/chapter0/0-2.cpp.i
.PHONY : chapter0/0-2.cpp.i

chapter0/0-2.s: chapter0/0-2.cpp.s
.PHONY : chapter0/0-2.s

# target to generate assembly for a file
chapter0/0-2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/0-2.dir/build.make CMakeFiles/0-2.dir/chapter0/0-2.cpp.s
.PHONY : chapter0/0-2.cpp.s

chapter01/1-1.o: chapter01/1-1.cpp.o
.PHONY : chapter01/1-1.o

# target to build an object file
chapter01/1-1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-1.dir/build.make CMakeFiles/1-1.dir/chapter01/1-1.cpp.o
.PHONY : chapter01/1-1.cpp.o

chapter01/1-1.i: chapter01/1-1.cpp.i
.PHONY : chapter01/1-1.i

# target to preprocess a source file
chapter01/1-1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-1.dir/build.make CMakeFiles/1-1.dir/chapter01/1-1.cpp.i
.PHONY : chapter01/1-1.cpp.i

chapter01/1-1.s: chapter01/1-1.cpp.s
.PHONY : chapter01/1-1.s

# target to generate assembly for a file
chapter01/1-1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-1.dir/build.make CMakeFiles/1-1.dir/chapter01/1-1.cpp.s
.PHONY : chapter01/1-1.cpp.s

chapter01/1-2.o: chapter01/1-2.cpp.o
.PHONY : chapter01/1-2.o

# target to build an object file
chapter01/1-2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-2.dir/build.make CMakeFiles/1-2.dir/chapter01/1-2.cpp.o
.PHONY : chapter01/1-2.cpp.o

chapter01/1-2.i: chapter01/1-2.cpp.i
.PHONY : chapter01/1-2.i

# target to preprocess a source file
chapter01/1-2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-2.dir/build.make CMakeFiles/1-2.dir/chapter01/1-2.cpp.i
.PHONY : chapter01/1-2.cpp.i

chapter01/1-2.s: chapter01/1-2.cpp.s
.PHONY : chapter01/1-2.s

# target to generate assembly for a file
chapter01/1-2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-2.dir/build.make CMakeFiles/1-2.dir/chapter01/1-2.cpp.s
.PHONY : chapter01/1-2.cpp.s

chapter01/1-3.o: chapter01/1-3.cpp.o
.PHONY : chapter01/1-3.o

# target to build an object file
chapter01/1-3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-3.dir/build.make CMakeFiles/1-3.dir/chapter01/1-3.cpp.o
.PHONY : chapter01/1-3.cpp.o

chapter01/1-3.i: chapter01/1-3.cpp.i
.PHONY : chapter01/1-3.i

# target to preprocess a source file
chapter01/1-3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-3.dir/build.make CMakeFiles/1-3.dir/chapter01/1-3.cpp.i
.PHONY : chapter01/1-3.cpp.i

chapter01/1-3.s: chapter01/1-3.cpp.s
.PHONY : chapter01/1-3.s

# target to generate assembly for a file
chapter01/1-3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-3.dir/build.make CMakeFiles/1-3.dir/chapter01/1-3.cpp.s
.PHONY : chapter01/1-3.cpp.s

chapter01/1-4.o: chapter01/1-4.cpp.o
.PHONY : chapter01/1-4.o

# target to build an object file
chapter01/1-4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-4.dir/build.make CMakeFiles/1-4.dir/chapter01/1-4.cpp.o
.PHONY : chapter01/1-4.cpp.o

chapter01/1-4.i: chapter01/1-4.cpp.i
.PHONY : chapter01/1-4.i

# target to preprocess a source file
chapter01/1-4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-4.dir/build.make CMakeFiles/1-4.dir/chapter01/1-4.cpp.i
.PHONY : chapter01/1-4.cpp.i

chapter01/1-4.s: chapter01/1-4.cpp.s
.PHONY : chapter01/1-4.s

# target to generate assembly for a file
chapter01/1-4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-4.dir/build.make CMakeFiles/1-4.dir/chapter01/1-4.cpp.s
.PHONY : chapter01/1-4.cpp.s

chapter01/1-5.o: chapter01/1-5.cpp.o
.PHONY : chapter01/1-5.o

# target to build an object file
chapter01/1-5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-5.dir/build.make CMakeFiles/1-5.dir/chapter01/1-5.cpp.o
.PHONY : chapter01/1-5.cpp.o

chapter01/1-5.i: chapter01/1-5.cpp.i
.PHONY : chapter01/1-5.i

# target to preprocess a source file
chapter01/1-5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-5.dir/build.make CMakeFiles/1-5.dir/chapter01/1-5.cpp.i
.PHONY : chapter01/1-5.cpp.i

chapter01/1-5.s: chapter01/1-5.cpp.s
.PHONY : chapter01/1-5.s

# target to generate assembly for a file
chapter01/1-5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-5.dir/build.make CMakeFiles/1-5.dir/chapter01/1-5.cpp.s
.PHONY : chapter01/1-5.cpp.s

chapter01/1-6.o: chapter01/1-6.cpp.o
.PHONY : chapter01/1-6.o

# target to build an object file
chapter01/1-6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-6.dir/build.make CMakeFiles/1-6.dir/chapter01/1-6.cpp.o
.PHONY : chapter01/1-6.cpp.o

chapter01/1-6.i: chapter01/1-6.cpp.i
.PHONY : chapter01/1-6.i

# target to preprocess a source file
chapter01/1-6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-6.dir/build.make CMakeFiles/1-6.dir/chapter01/1-6.cpp.i
.PHONY : chapter01/1-6.cpp.i

chapter01/1-6.s: chapter01/1-6.cpp.s
.PHONY : chapter01/1-6.s

# target to generate assembly for a file
chapter01/1-6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/1-6.dir/build.make CMakeFiles/1-6.dir/chapter01/1-6.cpp.s
.PHONY : chapter01/1-6.cpp.s

chapter01/String_exer.o: chapter01/String_exer.cpp.o
.PHONY : chapter01/String_exer.o

# target to build an object file
chapter01/String_exer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/String_exer.dir/build.make CMakeFiles/String_exer.dir/chapter01/String_exer.cpp.o
.PHONY : chapter01/String_exer.cpp.o

chapter01/String_exer.i: chapter01/String_exer.cpp.i
.PHONY : chapter01/String_exer.i

# target to preprocess a source file
chapter01/String_exer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/String_exer.dir/build.make CMakeFiles/String_exer.dir/chapter01/String_exer.cpp.i
.PHONY : chapter01/String_exer.cpp.i

chapter01/String_exer.s: chapter01/String_exer.cpp.s
.PHONY : chapter01/String_exer.s

# target to generate assembly for a file
chapter01/String_exer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/String_exer.dir/build.make CMakeFiles/String_exer.dir/chapter01/String_exer.cpp.s
.PHONY : chapter01/String_exer.cpp.s

chapter01/end_nl_exer.o: chapter01/end_nl_exer.cpp.o
.PHONY : chapter01/end_nl_exer.o

# target to build an object file
chapter01/end_nl_exer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/end_nl_exer.dir/build.make CMakeFiles/end_nl_exer.dir/chapter01/end_nl_exer.cpp.o
.PHONY : chapter01/end_nl_exer.cpp.o

chapter01/end_nl_exer.i: chapter01/end_nl_exer.cpp.i
.PHONY : chapter01/end_nl_exer.i

# target to preprocess a source file
chapter01/end_nl_exer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/end_nl_exer.dir/build.make CMakeFiles/end_nl_exer.dir/chapter01/end_nl_exer.cpp.i
.PHONY : chapter01/end_nl_exer.cpp.i

chapter01/end_nl_exer.s: chapter01/end_nl_exer.cpp.s
.PHONY : chapter01/end_nl_exer.s

# target to generate assembly for a file
chapter01/end_nl_exer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/end_nl_exer.dir/build.make CMakeFiles/end_nl_exer.dir/chapter01/end_nl_exer.cpp.s
.PHONY : chapter01/end_nl_exer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 0-10"
	@echo "... 0-2"
	@echo "... 1-1"
	@echo "... 1-2"
	@echo "... 1-3"
	@echo "... 1-4"
	@echo "... 1-5"
	@echo "... 1-6"
	@echo "... String_exer"
	@echo "... end_nl_exer"
	@echo "... chapter0/0-10.o"
	@echo "... chapter0/0-10.i"
	@echo "... chapter0/0-10.s"
	@echo "... chapter0/0-2.o"
	@echo "... chapter0/0-2.i"
	@echo "... chapter0/0-2.s"
	@echo "... chapter01/1-1.o"
	@echo "... chapter01/1-1.i"
	@echo "... chapter01/1-1.s"
	@echo "... chapter01/1-2.o"
	@echo "... chapter01/1-2.i"
	@echo "... chapter01/1-2.s"
	@echo "... chapter01/1-3.o"
	@echo "... chapter01/1-3.i"
	@echo "... chapter01/1-3.s"
	@echo "... chapter01/1-4.o"
	@echo "... chapter01/1-4.i"
	@echo "... chapter01/1-4.s"
	@echo "... chapter01/1-5.o"
	@echo "... chapter01/1-5.i"
	@echo "... chapter01/1-5.s"
	@echo "... chapter01/1-6.o"
	@echo "... chapter01/1-6.i"
	@echo "... chapter01/1-6.s"
	@echo "... chapter01/String_exer.o"
	@echo "... chapter01/String_exer.i"
	@echo "... chapter01/String_exer.s"
	@echo "... chapter01/end_nl_exer.o"
	@echo "... chapter01/end_nl_exer.i"
	@echo "... chapter01/end_nl_exer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

